import './WhoWeAre.css';
import { ReactComponent as People }  from '../../assets/images/people-fill.svg'
import { ReactComponent as Headset }  from '../../assets/images/headset.svg'
import { ReactComponent as Cash }  from '../../assets/images/cash-coin.svg'
import { AnimationOnScroll } from 'react-animation-on-scroll';
import "animate.css/animate.min.css";

function WhoWeAre() {

  return (
    <div id='WhoWeAre' className="WhoWeAre" >
        <h3>Type of services we offer</h3>
        <h2>Who We Are?</h2>
        <div className='filler'></div>
        <div className='item'>       
            <AnimationOnScroll animateOnce={true} animateIn="animate__fadeInRight">  
                <Cash/>   
                <h4>Guaranteed  Returns</h4>
                <p>TECH Capital has a 99.9% guarantee on each investment. We took what we learned over the years with stock  
                    trading and applied it to crypto trading and it worked better than anticipated. Make sure to contact us if you have 
                    any doubts and our team of experts will be more than happy to help.  
                    <br/> 
                    <br/> 
                    With us you have the highest ROI possible as we only take 2.55% of the income generated by our team. Investments start with as low as $10,000. 
                </p>
            </AnimationOnScroll> 
        </div>
        <div className='item'>
            <AnimationOnScroll animateOnce={true} animateIn="animate__fadeInRight">  
                <People />
                <h4>Dedicated Team</h4> 
                <p>We have a dedicated team working together to generate high incomes. TECH Capital only hires the best of the best to make sure that every challenge is solved efficiently. 
                    Over the years we have developed a great working dynamic where everyone knows exactly  
                    how to make the most money out of each trade. 
                    <br/> 
                    <br/> 
                    Are you interested in working for us?  
                </p> 
                <a href='#contactUs'><button>Available Jobs</button></a>
            </AnimationOnScroll> 
        </div>

        <div className='item'>
            <AnimationOnScroll animateOnce={true} animateIn="animate__fadeInRight">  
                <Headset />
                <h4>Superb Customer Support</h4> 
                <p> Sometimes unexpected things happen, and we know that. Every single one of our customers has a free 24/7  
                    contact our support team. They will help with any query and solve every issue to the best of their abilities. 
                    <br/> 
                    <br/> 
                    Want to find out more now? 
                </p> 
                <a href='#contactUs'><button>Contact Support</button></a>
            </AnimationOnScroll> 

        </div>
</div>
  );
}

export default WhoWeAre;
